source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'rake_terraform', '~> 1.9'
gem 'rake_docker', '~> 2.11'
gem 'rake_ssh', '~> 0.2'
gem 'rake_easy_rsa', '~> 0.4'
gem 'rake_gpg', '~> 0.10'
gem 'rake_template', '~> 0.2'
gem 'confidante', '~> 0.21'
gem 'semantic', '~> 1.6'
