---
region: "eu-west-2"
component: "openvpn-example"

private_network_cidr: "10.0.0.0/16"

service_desired_count: 3

openvpn_server_image: "infrablocks/openvpn-aws:0.10.0"
openvpn_server_service_container_port: 1194
openvpn_server_service_host_port: 1194
openvpn_server_service_lb_port: 1194
openvpn_server_allow_cidrs:
  - "0.0.0.0/0"

storage_bucket_name: "infrablocks-%{hiera('component')}-%{hiera('deployment_identifier')}"
secrets_bucket_name: "%{hiera('storage_bucket_name')}"

domain_state_bucket_region: "%{hiera('region')}"
domain_state_bucket_name: "%{hiera('storage_bucket_name')}"
domain_state_bucket_is_encrypted: "true"
domain_state_key: "domain/deployments/%{hiera('deployment_identifier')}.tfstate"

network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_name: "%{hiera('storage_bucket_name')}"
network_state_bucket_is_encrypted: "true"
network_state_key: "network/deployments/%{hiera('deployment_identifier')}.tfstate"

cluster_state_bucket_region: "%{hiera('region')}"
cluster_state_bucket_name: "%{hiera('storage_bucket_name')}"
cluster_state_bucket_is_encrypted: "true"
cluster_state_key: "cluster/deployments/%{hiera('deployment_identifier')}.tfstate"

service_state_bucket_region: "%{hiera('region')}"
service_state_bucket_name: "%{hiera('storage_bucket_name')}"
service_state_bucket_is_encrypted: "true"
service_state_key: "service/deployments/%{hiera('deployment_identifier')}.tfstate"
