---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"

  deployment_identifier: "%{hiera('deployment_identifier')}"

  private_network_cidr: "%{hiera('private_network_cidr')}"

  service_desired_count: "%{hiera('service_desired_count')}"

  openvpn_server_image: "%{hiera('openvpn_server_image')}"
  openvpn_server_service_container_port: "%{hiera('openvpn_server_service_container_port')}"
  openvpn_server_service_host_port: "%{hiera('openvpn_server_service_host_port')}"
  openvpn_server_service_lb_port: "%{hiera('openvpn_server_service_lb_port')}"
  openvpn_server_allow_cidrs: "%{hiera('openvpn_server_allow_cidrs')}"

  secrets_bucket_name: "%{hiera('secrets_bucket_name')}"

  domain_state_bucket_name: "%{hiera('domain_state_bucket_name')}"
  domain_state_key: "%{hiera('domain_state_key')}"
  domain_state_bucket_region: "%{hiera('domain_state_bucket_region')}"
  domain_state_bucket_is_encrypted: "%{hiera('domain_state_bucket_is_encrypted')}"

  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_key: "%{hiera('network_state_key')}"
  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"

  cluster_state_bucket_name: "%{hiera('cluster_state_bucket_name')}"
  cluster_state_key: "%{hiera('cluster_state_key')}"
  cluster_state_bucket_region: "%{hiera('cluster_state_bucket_region')}"
  cluster_state_bucket_is_encrypted: "%{hiera('cluster_state_bucket_is_encrypted')}"

backend_config:
  bucket: "%{hiera('service_state_bucket_name')}"
  key: "%{hiera('service_state_key')}"
  region: "%{hiera('service_state_bucket_region')}"
  encrypt: "%{hiera('service_state_bucket_is_encrypted')}"
